[project]
name = "skills-introduction-to-github"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "python-decouple>=3.8",
    "requests>=2.32.3",
    "selenium>=4.28.0",
]
